# Generated by Django 3.1.6 on 2021-02-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='в долларах США', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='image',
            field=models.ImageField(upload_to='static/actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to='static/movies/', verbose_name='Постер'),
        ),
    ]
